### PR TITLE
r? ianbicking Fixes #500 Implement jumping to a text clip.

### LINKED ISSUE #500: Jumping to text clips doesn't work

### PR DESCRIPTION
**Pull request by fzzzy**

### CODE REVIEW

File: server/src/static/js/content-helper.js [hunk 1]
```diff
@@ -33,24 +33,40 @@ window.addEventListener(
...
-    right: loc.right
+    top: 0,
+    bottom: 0,
+    left: 0,
+    right: 0
   };
-  let topLeft = findElement(loc.topLeftElement);
+
+  if (clip.text) {
+    topLeft = findElement("#" + clip.text.location.selectionStart);
```
Comment (ianb) [inline server/src/static/js/content-helper.js]: Did I use inconsistent selectors for text and images?  Yuck.  I guess maybe for now we should open a ticket to straighten that out.
